<?php

/**
 * @var $block \Overdose\Lesson4\Block\Overdose
 * @var $viewModel \Overdose\Lesson4\ViewModel\One
 */

$viewModel = $block->getViewModel();

?>

<h1><?= $viewModel->getName('Sergio') ?></h1>
<table border="1">
    <tr>
        <td>Имя</td>
        <td>Возраст</td>
        <td>Заметки</td>
    </tr>
<?php foreach ($viewModel->showFriendsList() as $item):?>

    <?php echo
        '<tr>' .
        '<td>' . $item['name'] . '</td>' .
        '<td>' . $item['age'] . '</td>' .
        '<td>' . $item['notes'] . '</td>' .
        '</tr>'
    ;?>

    <?php endforeach; ?>
</table>
