<?php

/**
 * @var $block \Overdose\Lesson6\Block\Overdose
 * @var $viewModel \Overdose\Lesson6\ViewModel\One
 */

$viewModel = $block->getViewModel();

?>

<h1><?= $viewModel->getName('Sergio') ?></h1>
<table border="1">
    <tr>
        <td><?= __('Name')?></td>
        <td><?= __('Age')?></td>
        <td><?= __('Notes')?></td>
    </tr>
    <?php foreach ($viewModel->showFriendsList() as $item):?>

        <?php echo
            '<tr>' .
            '<td>' . $item['name'] . '</td>' .
            '<td>' . $item['age'] . '</td>' .
            '<td>' . $item['notes'] . '</td>' .
            '</tr>'
        ;?>

    <?php endforeach; ?>
</table>


